### PR TITLE
API Rewrite/Libuv Shim

### PR DESCRIPTION
**Pull request by miversen33**
This will be a dangling PR so I can start linking issues to it.

### CODE REVIEW

**Comment by miversen33** [comment]
There is alot going on in this PR so its worth calling out each _big_ piece of this.
Note: This is an abnormal PR, usually features/changes wont be included in one big merge like this. Consider this a 1 time thing.

This PR addresses several issues:
- #61 
- #44 
- #28 

The biggest of which is #28 which effectively required a rewrite of the core API. This rewrite was not able to be done (reasonably) in small enough chunks to warrant a better PR (sorry about that future Mike, I'm sure you will hate this).

**Additionally, this PR includes a backwards breaking change due to #61 **. This is unlikely to affect anyone as it does not appear that anyone has started integrating with Netman yet. But its still worth calling out. Sorry 😦 

There will likely be a bit more work that needs to be done to get `libruv` (The netman libuv shim) fully functional.

Note: Libruv is a convenience/shim layer and will _not_ get any updates for specific file explorers. Explorers **should** integrate netman into themselves as a source if they wish to use Netman. 

More details will follow.

**Comment by miversen33** [comment]
For anyone watching this PR, all that we have left is to flesh out the Unit Tests for the changes to ensure they are "stable". 
Adding a target date to the Milestone

**Comment by luxus** [comment]
looking forward to see this get merged :D

**Comment by miversen33** [comment]
I'm slowing picking through the various Unit Tests I need to have in place to get this in a spot I feel comfortable merging into v1.1. I have a few more tests left on the "SSH" provider, and then I should be a spot where I can run v1.1 in "production" for some real world testing. I have been running this branch in production for a few months but am still encountering some issues which is why there are _so many_ commits on this PR (vs a more traditional PR which is a few commits and encompasses one idea/feature/fix).

Its getting there though :)

**Comment by luxus** [comment]
oh sounds wonderful, then i will maybe try this PR even before the merge

**Comment by miversen33** [comment]
This was inadvertanly closed but Im kinda ok with it as v1.1 is in a good enough spot for me to move forward with getting configuration development started (new branch incoming).

**Pull request merged**
